version: "3.8"

services:
  backend:
    build: ./backend
    container_name: mock-http-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/app/db:rw
    environment:
      - NODE_ENV=production
      - PORT=3000

  frontend:
    build: ./frontend
    container_name: mock-http-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
